sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pioblaz/fibonacci -f Dockerfile.dev1 .

script:
  - docker run -e CI=true pioblaz/fibonacci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test"
  env: "dockertest-env"
  bucket_name: "elasticbeanstalk-us-east-2-039699603980"
  bucket_path: "docker-test"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
